<?php

/**
 * Compiles a `theme.json` payload into a `:root { --wp--preset--*: …; }`
 * CSS block.
 *
 * Mirrors WordPress's `--wp--preset--{category}--{slug}` naming so block
 * markup that already references those tokens (every Gutenberg core block's
 * preset attributes do) just works on the public site without each
 * consumer re-implementing the bridge.
 *
 * Categories covered today: `color.palette[]`, `color.gradient[]`,
 * `typography.fontSizes[]`, `spacing.spacingSizes[]`. Anything else passes
 * through untouched so theme.json files keep validating against WP's
 * schema while only the recognised sections drive CSS output.
 *
 * @package    ArtisanPack_UI
 * @subpackage VisualEditorRendererBlade
 *
 * @author     Jacob Martella <me@jacobmartella.com>
 *
 * @since      1.1.0
 */

declare( strict_types=1 );

namespace ArtisanPackUI\VisualEditorRendererBlade\Services;

class ThemeJsonTokensCompiler
{
	/**
	 * Compile a theme.json array into a `:root` CSS block, or '' when the
	 * input carries no recognised tokens.
	 *
	 * @since 1.1.0
	 *
	 * @param  array<string, mixed>  $themeJson  Decoded theme.json payload.
	 */
	public function compile( array $themeJson ): string
	{
		$settings = is_array( $themeJson['settings'] ?? null ) ? $themeJson['settings'] : [];

		$declarations = array_merge(
			$this->compilePresetList( $settings, [ 'color', 'palette' ], 'color', 'color' ),
			$this->compilePresetList( $settings, [ 'color', 'gradient' ], 'gradient', 'gradient' ),
			$this->compilePresetList( $settings, [ 'typography', 'fontSizes' ], 'font-size', 'size' ),
			$this->compilePresetList( $settings, [ 'spacing', 'spacingSizes' ], 'spacing', 'size' ),
			$this->compileLayoutSizes( $settings ),
		);

		$root = [] === $declarations ? '' : ":root {\n\t" . implode( "\n\t", $declarations ) . "\n}";

		$layout = $this->compileLayoutRules( $settings );

		if ( '' === $root ) {
			return $layout;
		}

		if ( '' === $layout ) {
			return $root;
		}

		return $root . "\n\n" . $layout;
	}

	/**
	 * Emit `--wp--style--global--content-size` and
	 * `--wp--style--global--wide-size` custom properties from
	 * `settings.layout` so the layout rules generated by
	 * {@see compileLayoutRules} resolve against the theme's values.
	 *
	 * @since 1.1.0
	 *
	 * @param  array<string, mixed>  $settings
	 *
	 * @return list<string>
	 */
	protected function compileLayoutSizes( array $settings ): array
	{
		$layout = $settings['layout'] ?? null;

		if ( ! is_array( $layout ) ) {
			return [];
		}

		$declarations = [];

		$contentSize = isset( $layout['contentSize'] ) && is_string( $layout['contentSize'] ) ? trim( $layout['contentSize'] ) : '';
		$wideSize    = isset( $layout['wideSize'] ) && is_string( $layout['wideSize'] ) ? trim( $layout['wideSize'] ) : '';

		if ( '' !== $contentSize ) {
			$declarations[] = '--wp--style--global--content-size: ' . $contentSize . ';';
		}

		if ( '' !== $wideSize ) {
			$declarations[] = '--wp--style--global--wide-size: ' . $wideSize . ';';
		}

		return $declarations;
	}

	/**
	 * Emit the layout rules that make `alignwide` / `alignfull` actually
	 * take effect on root-level constrained groups (Keystone #50).
	 *
	 * WordPress-FSE themes do this at the template level by wrapping
	 * post content in a `.wp-block-post-content` container that
	 * provides a parent context for `.is-layout-constrained > .alignwide`
	 * to match against. Our renderer-blade output drops blocks directly
	 * into the consumer's `<main>` / template wrapper, which carries no
	 * such marker — without these rules the alignment classes ride on
	 * the section but no CSS sizes the section accordingly.
	 *
	 * The rules target the constrained group's own classes (not a
	 * parent-relative selector), so they apply whether the group sits
	 * at the page root or inside another container. The default case
	 * (constrained group without an alignment override) is left alone
	 * so themes that style children-of-constrained directly aren't
	 * double-constrained.
	 *
	 * @since 1.1.0
	 *
	 * @param  array<string, mixed>  $settings
	 */
	protected function compileLayoutRules( array $settings ): string
	{
		$layout = $settings['layout'] ?? null;

		if ( ! is_array( $layout ) ) {
			return '';
		}

		$hasContentSize = isset( $layout['contentSize'] ) && is_string( $layout['contentSize'] ) && '' !== trim( $layout['contentSize'] );
		$hasWideSize    = isset( $layout['wideSize'] ) && is_string( $layout['wideSize'] ) && '' !== trim( $layout['wideSize'] );

		if ( ! $hasContentSize && ! $hasWideSize ) {
			return '';
		}

		$rules = [];

		// Rule set A — the constrained group's OWN classes. Applies
		// whether the group is at the page root or nested inside
		// another container; covers the common "section with an
		// alignment override" case authors hit in the editor.
		if ( $hasWideSize ) {
			$rules[] = ".wp-block-group.is-layout-constrained.alignwide {\n"
				. "\tmax-width: var(--wp--style--global--wide-size);\n"
				. "\tmargin-left: auto;\n"
				. "\tmargin-right: auto;\n"
				. '}';
		}

		// `alignfull` is unconditional — full-bleed is the same regardless
		// of theme.json values. Emit it whenever ANY layout is configured
		// so authors can toggle it on without the renderer caring whether
		// `wideSize` happened to be declared.
		$rules[] = ".wp-block-group.is-layout-constrained.alignfull {\n"
			. "\tmax-width: none;\n"
			. '}';

		// Rule set B — children of an opt-in `.wp-block-post-content`
		// container. Mirrors WP-FSE's post-content layout: when a theme
		// wraps its page content in `<main class="wp-block-post-content
		// is-layout-constrained">`, the children get the canonical
		// "default = content-size, wide = wide-size, full = no max"
		// behavior. Themes that don't add the class keep the old
		// "container is full-bleed unless aligned" behavior — the
		// opt-in keeps this from clashing with header / footer
		// wrappers that are intentionally full-width.
		if ( $hasContentSize ) {
			$rules[] = ".wp-block-post-content.is-layout-constrained > :where(:not(.alignwide):not(.alignfull):not(.alignleft):not(.alignright)) {\n"
				. "\tmax-width: var(--wp--style--global--content-size);\n"
				. "\tmargin-left: auto;\n"
				. "\tmargin-right: auto;\n"
				. '}';
		}

		if ( $hasWideSize ) {
			$rules[] = ".wp-block-post-content.is-layout-constrained > .alignwide {\n"
				. "\tmax-width: var(--wp--style--global--wide-size);\n"
				. "\tmargin-left: auto;\n"
				. "\tmargin-right: auto;\n"
				. '}';
		}

		$rules[] = ".wp-block-post-content.is-layout-constrained > .alignfull {\n"
			. "\tmax-width: none;\n"
			. '}';

		return implode( "\n\n", $rules );
	}

	/**
	 * Walk `$settings[path[0]][path[1]]` if it exists and return one CSS
	 * declaration per entry, of the form
	 * `--wp--preset--{$category}--{$slug}: {$value};`.
	 *
	 * Entries missing either `slug` or the value key are skipped silently
	 * — theme.json validation is the consumer's responsibility, the
	 * compiler stays defensive so a malformed entry doesn't blow up the
	 * whole render.
	 *
	 * @since 1.1.0
	 *
	 * @param  array<string, mixed>  $settings
	 * @param  array{0: string, 1: string}  $path
	 * @return list<string>
	 */
	protected function compilePresetList( array $settings, array $path, string $category, string $valueKey ): array
	{
		$list = $settings[ $path[0] ][ $path[1] ] ?? null;

		if ( ! is_array( $list ) ) {
			return [];
		}

		$declarations = [];

		foreach ( $list as $entry ) {
			if ( ! is_array( $entry ) ) {
				continue;
			}

			$slug  = isset( $entry['slug'] ) && is_string( $entry['slug'] ) ? trim( $entry['slug'] ) : '';
			$value = isset( $entry[ $valueKey ] ) && is_string( $entry[ $valueKey ] ) ? trim( $entry[ $valueKey ] ) : '';

			if ( '' === $slug || '' === $value ) {
				continue;
			}

			$declarations[] = sprintf(
				'--wp--preset--%s--%s: %s;',
				$this->slug( $category ),
				$this->slug( $slug ),
				$value
			);
		}

		return $declarations;
	}

	/**
	 * Normalise a slug for use in a CSS custom property name. Mirrors
	 * WordPress's behaviour: lowercase, ASCII-safe, hyphenated.
	 *
	 * @since 1.1.0
	 */
	protected function slug( string $value ): string
	{
		$value = strtolower( $value );

		return (string) preg_replace( '/[^a-z0-9\-]/', '-', $value );
	}
}
