<?php

/**
 * Generated `fonts.css` bundle builder.
 *
 * Rebuilds the single `fonts.css` file the Font Library serves to both the
 * editor canvas and the public site. The bundle carries one `@font-face` rule
 * per installed {@see FontFace}, plus a `:root` block of
 * `--wp--preset--font-family--{slug}` custom properties so the block style
 * pipeline can reference installed families the same way it references
 * theme.json font presets.
 *
 * {@see generate()} writes atomically — the CSS lands in a sibling temp file
 * that is renamed over the live path — so a failed rebuild leaves the previous
 * `fonts.css` in place rather than truncating it.
 *
 * @package    ArtisanPack_UI
 * @subpackage VisualEditor
 *
 * @author     Jacob Martella <me@jacobmartella.com>
 *
 * @since      1.7.0
 */

declare( strict_types=1 );

namespace ArtisanPackUI\VisualEditor\Fonts\Services;

use ArtisanPackUI\VisualEditor\Fonts\Exceptions\FontFileWriteException;
use ArtisanPackUI\VisualEditor\Fonts\Models\Font;
use ArtisanPackUI\VisualEditor\Fonts\Models\FontFace;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Throwable;

class FontsCssGenerator
{
	/**
	 * @param  string|null  $disk     The storage disk, or null to read config at call time.
	 * @param  string|null  $cssPath  The bundle path under the disk, or null to read config.
	 */
	public function __construct(
		protected ?string $disk = null,
		protected ?string $cssPath = null,
	) {
	}

	/**
	 * Build the bundle CSS from every installed font, without touching disk.
	 *
	 * @since 1.7.0
	 */
	public function build(): string
	{
		$fonts = Font::query()
			->with( [ 'faces' => static fn ( $query ) => $query->orderBy( 'weight' )->orderBy( 'style' ) ] )
			->orderBy( 'family' )
			->get();

		$faceRules = [];
		$presets   = [];

		foreach ( $fonts as $font ) {
			foreach ( $font->faces as $face ) {
				$faceRules[] = $this->faceRule( $font, $face );
			}

			$presets[] = sprintf(
				"\t--wp--preset--font-family--%s: %s;",
				$this->presetSlug( $font->slug ),
				$this->familyStack( $font->family )
			);
		}

		$blocks = [ "/* Generated by ArtisanPack UI Visual Editor Font Library. Do not edit by hand. */" ];

		if ( [] !== $faceRules ) {
			$blocks[] = implode( "\n\n", $faceRules );
		}

		if ( [] !== $presets ) {
			$blocks[] = ":root {\n" . implode( "\n", $presets ) . "\n}";
		}

		return implode( "\n\n", $blocks ) . "\n";
	}

	/**
	 * Rebuild the bundle and write it atomically to the configured disk.
	 *
	 * The CSS is written to a sibling temp file first, then renamed over the
	 * live path; a failure at any point cleans the temp file up and leaves the
	 * previous bundle untouched.
	 *
	 * @since 1.7.0
	 *
	 * @return string The CSS that was written.
	 */
	public function generate(): string
	{
		$css      = $this->build();
		$disk     = Storage::disk( $this->diskName() );
		$path     = $this->path();
		$tempPath = $path . '.' . Str::random( 12 ) . '.tmp';

		try {
			if ( false === $disk->put( $tempPath, $css ) ) {
				throw new FontFileWriteException( sprintf(
					'Failed to stage the fonts.css bundle at "%s".',
					$tempPath
				) );
			}

			// Rename over the live path. On the local driver this is an atomic
			// rename(2), so a reader never observes a half-written bundle.
			if ( false === $disk->move( $tempPath, $path ) ) {
				throw new FontFileWriteException( sprintf(
					'Failed to move the staged fonts.css bundle into place at "%s".',
					$path
				) );
			}
		} catch ( Throwable $e ) {
			if ( $disk->exists( $tempPath ) ) {
				$disk->delete( $tempPath );
			}

			if ( $e instanceof FontFileWriteException ) {
				throw $e;
			}

			throw new FontFileWriteException(
				'Failed to write the fonts.css bundle.',
				0,
				$e
			);
		}

		return $css;
	}

	/**
	 * Read the generated bundle from disk, or an empty string when it has not
	 * been generated yet.
	 *
	 * @since 1.7.0
	 */
	public function read(): string
	{
		$disk = Storage::disk( $this->diskName() );

		if ( ! $disk->exists( $this->path() ) ) {
			return '';
		}

		return (string) $disk->get( $this->path() );
	}

	/**
	 * Whether the generated bundle exists on disk.
	 *
	 * @since 1.7.0
	 */
	public function exists(): bool
	{
		return Storage::disk( $this->diskName() )->exists( $this->path() );
	}

	/**
	 * The public URL of the generated bundle, or null when the disk exposes no
	 * URL or the bundle does not exist.
	 *
	 * @since 1.7.0
	 */
	public function url(): ?string
	{
		if ( ! $this->exists() ) {
			return null;
		}

		try {
			return Storage::disk( $this->diskName() )->url( $this->path() );
		} catch ( Throwable ) {
			return null;
		}
	}

	/**
	 * A cache-busting version token for the bundle — its last-modified time, or
	 * null when the bundle does not exist.
	 *
	 * @since 1.7.0
	 */
	public function version(): ?int
	{
		if ( ! $this->exists() ) {
			return null;
		}

		try {
			return Storage::disk( $this->diskName() )->lastModified( $this->path() );
		} catch ( Throwable ) {
			return null;
		}
	}

	/**
	 * The storage disk the bundle is written to.
	 *
	 * @since 1.7.0
	 */
	public function diskName(): string
	{
		return $this->disk ?? (string) config( 'artisanpack.visual-editor.fonts.disk', 'public' );
	}

	/**
	 * The bundle path under the disk, trimmed of surrounding slashes.
	 *
	 * @since 1.7.0
	 */
	public function path(): string
	{
		$path = $this->cssPath ?? (string) config( 'artisanpack.visual-editor.fonts.css_path', 'visual-editor/fonts/fonts.css' );

		return ltrim( $path, '/' );
	}

	/**
	 * Compose a single `@font-face` rule for a face.
	 *
	 * @since 1.7.0
	 */
	protected function faceRule( Font $font, FontFace $face ): string
	{
		$src = $this->faceUrl( $face );

		// Each self-hosted face file is a single static instance (Google and
		// Bunny serve one WOFF2 per weight), so the rule carries that face's
		// own weight. Parsed axis ranges live on the face for the typography
		// picker (#636); they are not a `@font-face` weight range here.
		return sprintf(
			"@font-face {\n\tfont-family: %s;\n\tfont-style: %s;\n\tfont-weight: %d;\n\tfont-display: swap;\n\tsrc: url(\"%s\") format(\"%s\");\n}",
			$this->quoteFamily( $font->family ),
			'italic' === $face->style ? 'italic' : 'normal',
			$face->weight,
			$src,
			$this->cssFormat( $face->format )
		);
	}

	/**
	 * Resolve the browser-facing URL for a face file, honoring the face's own
	 * stored disk.
	 *
	 * @since 1.7.0
	 */
	protected function faceUrl( FontFace $face ): string
	{
		try {
			return Storage::disk( $face->disk )->url( $face->path );
		} catch ( Throwable ) {
			// A disk with no configured URL still yields a usable root-relative
			// path so the bundle references a stable location.
			return '/' . ltrim( $face->path, '/' );
		}
	}

	/**
	 * The `--wp--preset--font-family--*` custom-property value: the family name
	 * followed by a generic fallback so text still renders before the face
	 * loads.
	 *
	 * @since 1.7.0
	 */
	protected function familyStack( string $family ): string
	{
		return $this->quoteFamily( $family ) . ', sans-serif';
	}

	/**
	 * Quote a family name for the CSS string context so a crafted family name
	 * cannot break out of it.
	 *
	 * A provider's catalog is untrusted once a third-party or custom
	 * `FontProvider` is registered, and the family name is interpolated into a
	 * bundle that is injected into the editor iframe and served on the public
	 * site. Escaping only the quote and backslash is not enough: an unescaped
	 * newline terminates the CSS string token and lets trailing text inject new
	 * rules, and `<`/`>` could close the iframe's `<style>` element. Strip C0/C1
	 * control characters and angle brackets — no real family name contains them
	 * — then escape the backslash and quote that stay meaningful in the string.
	 *
	 * @since 1.7.0
	 */
	protected function quoteFamily( string $family ): string
	{
		$family = preg_replace( '/[\x00-\x1F\x7F-\x9F<>]/u', '', $family ) ?? '';
		$family = str_replace( [ '\\', '"' ], [ '\\\\', '\\"' ], $family );

		return '"' . $family . '"';
	}

	/**
	 * Normalize a stored file format into a CSS `format()` token.
	 *
	 * @since 1.7.0
	 */
	protected function cssFormat( string $format ): string
	{
		return 'ttf' === strtolower( $format ) ? 'truetype' : strtolower( $format );
	}

	/**
	 * Sanitize a font slug for use in a CSS custom-property name.
	 *
	 * @since 1.7.0
	 */
	protected function presetSlug( string $slug ): string
	{
		return Str::slug( $slug );
	}

	/**
	 * Render a numeric axis bound without a trailing `.0`.
	 *
	 * @since 1.7.0
	 */
	protected function trimNumber( mixed $value ): string
	{
		$float = (float) $value;

		return rtrim( rtrim( sprintf( '%.3f', $float ), '0' ), '.' );
	}
}
